script:
    - wget https://product-dist.ballerina.io/downloads/1.2.0/ballerina-linux-installer-x64-1.2.0.deb
    - sudo dpkg -i ballerina-linux-installer-x64-1.2.0.deb
    - sudo apt-get install -f
    - ballerina --version
    - ballerina build -c oauth2
    - ballerina run oauth2
